name: Deploy
on:
  push:
    branches: web
  pull_request:
    branches: web

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build step
        run: deno task build # 📝 Update the build command(s)

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "brianm-denoplay-web"
          entrypoint: "main.ts" # 📝 Update the entrypoint
          root: "."
